[zpool]
use_template = production

#############################
# templates below this line #
#############################

[template_production]
frequently = 0
hourly = 0
daily = 14
monthly = 3
yearly = 1
autosnap = yes
autoprune = yes
